/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 
package view;

import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
 
import mmrnovelsummaryindotext.TextSummaryOperator;
import mmrnovelsummaryindotext.IndoTextReader;
import mmrnovelsummaryindotext.TextPreProcessing;
import textprocessing.IndoText; 
import textprocessing.Sentence;
import utils.ExtensionFileFilter;
import utils.Util;

/**
 *
 * @author Fiqih Amrullah
 */
public class FormTextSummary extends javax.swing.JFrame 
{
    private JFileChooser jfc; 
    private IndoText article;  
    private IndoText summerizedarticle,manualsummerizedarticle;
    private TextSummaryOperator aso;

    /** Creates new form FormNovelSummary */
    public FormTextSummary() 
    {
        initComponents();
        Util.LookAndFeel(this);
        Util.TengahWindow(this);
        setResizable(false);
        summerizedarticle = null;
        setTitle("Peringkasan Teks dengan Metode MMR");
    }
    
    private int openDialogFile() 
    {
       jfc = new JFileChooser();
       FileFilter filter1 = new ExtensionFileFilter("Text Files", new String[] { "txt"});
       jfc.setFileFilter(filter1);
       
       return jfc.showOpenDialog(null);
    }
   
   private void showContent(String title,IndoText article)
   {     
       jTxtIsi.setText(article.getIsiArtikel());
   }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtIsi = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jbtnRingkas = new javax.swing.JButton();
        jbtnBrowseArticle = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTxtHasilRingkasan = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jlblJudul = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtHasilPraprocess = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtxtLogTokenizing = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtxtLogStopwordRemoval = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtxtLogAfterStemming = new javax.swing.JTextArea();
        jlblStat = new javax.swing.JLabel();
        jbtnBandingManual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PERINGKASAN OTOMATIS DENGAN METODE MMR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 620, 40));

        jLabel2.setText("Isi:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jTxtIsi.setColumns(20);
        jTxtIsi.setLineWrap(true);
        jTxtIsi.setRows(5);
        jTxtIsi.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTxtIsi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 360, 360));

        jLabel3.setText("Hasil Peringkasan:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        jbtnRingkas.setText("Ringkas");
        jbtnRingkas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRingkasActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnRingkas, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 90, 60));

        jbtnBrowseArticle.setText("Browse..");
        jbtnBrowseArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseArticleActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowseArticle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 40));

        jLabel5.setText("Pra Process:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, -1));

        jTxtHasilRingkasan.setColumns(20);
        jTxtHasilRingkasan.setLineWrap(true);
        jTxtHasilRingkasan.setRows(5);
        jTxtHasilRingkasan.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTxtHasilRingkasan);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 370, 140));

        jLabel4.setText("Judul :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 20));

        jlblJudul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true), 2));
        getContentPane().add(jlblJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 790, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 870, 10));

        jTxtHasilPraprocess.setColumns(20);
        jTxtHasilPraprocess.setRows(5);
        jScrollPane2.setViewportView(jTxtHasilPraprocess);

        jTabbedPane1.addTab("Pecahan Kalimat", jScrollPane2);

        jtxtLogTokenizing.setColumns(20);
        jtxtLogTokenizing.setRows(5);
        jScrollPane4.setViewportView(jtxtLogTokenizing);

        jTabbedPane1.addTab("Tokenizing", jScrollPane4);

        jtxtLogStopwordRemoval.setColumns(20);
        jtxtLogStopwordRemoval.setRows(5);
        jScrollPane5.setViewportView(jtxtLogStopwordRemoval);

        jTabbedPane1.addTab("Stopword Removal", jScrollPane5);

        jtxtLogAfterStemming.setColumns(20);
        jtxtLogAfterStemming.setRows(5);
        jScrollPane6.setViewportView(jtxtLogAfterStemming);

        jTabbedPane1.addTab("After Stemming", jScrollPane6);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 370, 150));

        jlblStat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblStat.setText("-");
        jlblStat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true)));
        getContentPane().add(jlblStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 370, 30));

        jbtnBandingManual.setText("Banding Manual >>");
        jbtnBandingManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBandingManualActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBandingManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 313, 130, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jbtnRingkasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRingkasActionPerformed
// TODO add your handling code here:
   if (jlblJudul.getText().equals("")) 
   {
       JOptionPane.showMessageDialog(this, "File yang akan diringkas Belum terpilih","",JOptionPane.WARNING_MESSAGE);
   }else 
   {
        aso = new TextSummaryOperator(article, jTxtHasilPraprocess,jtxtLogTokenizing,jtxtLogStopwordRemoval,jtxtLogAfterStemming);
        summerizedarticle = aso.summarizeArticle();
        jTxtHasilRingkasan.setText(summerizedarticle.getIsiArtikel());
   }
    
}//GEN-LAST:event_jbtnRingkasActionPerformed

private void jbtnBrowseArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseArticleActionPerformed
// TODO add your handling code here:
     if (openDialogFile()==JFileChooser.APPROVE_OPTION)
      {
         if (jfc.getSelectedFile().getAbsolutePath().endsWith("txt")) 
         {
             article = IndoTextReader.readContent(jfc.getSelectedFile());
             jlblJudul.setText(article.getJudul());
             showContent(jfc.getSelectedFile().getName(), article);
         }else 
         {
             JOptionPane.showMessageDialog(this, "File harus berformat teks (.txt) ","",JOptionPane.WARNING_MESSAGE);
         }
         
      }
}//GEN-LAST:event_jbtnBrowseArticleActionPerformed

private void jbtnBandingManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBandingManualActionPerformed
// TODO add your handling code here:
        if (summerizedarticle!=null)
        {
                if (openDialogFile()==JFileChooser.APPROVE_OPTION)
                  {
                     if (jfc.getSelectedFile().getAbsolutePath().endsWith("txt")) 
                     {
                         manualsummerizedarticle = IndoTextReader.readContent(jfc.getSelectedFile());
                         List<Sentence>  listmanualsentences = TextPreProcessing.splitArticle(manualsummerizedarticle);               
                         System.out.println("Total Kalimat Manual : " + listmanualsentences.size());

                         String txtringkasan = summerizedarticle.getIsiArtikel();
                         int irisan=0;
                         for(int i=0;i<listmanualsentences.size();i++)
                         {
                             Sentence sentence = listmanualsentences.get(i);
                             if (txtringkasan.contains(listmanualsentences.get(i).getText()))
                             {
                                 irisan++;
                             }
                         }
                         //Precisi
                         double precision = (double) irisan / aso.getNumberOfSummarizedText();             
                         //Recall
                         double recall = (double) irisan/ listmanualsentences.size();
                         double fmeasure = (2*precision*recall)/(precision+recall);

                         String strprecision  =String.format("%.2f", precision);
                         String strrecall  =String.format("%.2f", recall);
                         String strfmeasure  =String.format("%.2f", fmeasure);
                         
                         jlblStat.setText("Precisi :" + strprecision + " , Recall :" + strrecall + " ,FMeasure :" + strfmeasure);
                         

                     }else 
                     {
                         JOptionPane.showMessageDialog(this, "File harus berformat teks (.txt) ","",JOptionPane.WARNING_MESSAGE);
                     }         
                  }
        }else{
            JOptionPane.showMessageDialog(this, "Anda Belum Meringkas Apapun!","Belum Bisa Banding",JOptionPane.WARNING_MESSAGE);
        }
}//GEN-LAST:event_jbtnBandingManualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTextSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTextSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTextSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTextSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormTextSummary().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTxtHasilPraprocess;
    private javax.swing.JTextArea jTxtHasilRingkasan;
    private javax.swing.JTextArea jTxtIsi;
    private javax.swing.JButton jbtnBandingManual;
    private javax.swing.JButton jbtnBrowseArticle;
    private javax.swing.JButton jbtnRingkas;
    private javax.swing.JLabel jlblJudul;
    private javax.swing.JLabel jlblStat;
    private javax.swing.JTextArea jtxtLogAfterStemming;
    private javax.swing.JTextArea jtxtLogStopwordRemoval;
    private javax.swing.JTextArea jtxtLogTokenizing;
    // End of variables declaration//GEN-END:variables
}
